name: collect last 13 years

on:
  workflow_dispatch:
    inputs:
      exam:
        description: "Exam to collect (JAMB, POSTUTME, GST)"
        required: true
        default: "JAMB"
      years_back:
        description: "How many recent years to pull"
        required: true
        default: "13"
      polite_delay_ms:
        description: "Delay between calls in ms"
        required: true
        default: "150"

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      MYQUEST_KEY: ${{ secrets.MYQUEST_KEY }}
      EXAM: ${{ github.event.inputs.exam }}
      YEARS_BACK: ${{ github.event.inputs.years_back }}
      POLITE_DELAY_MS: ${{ github.event.inputs.polite_delay_ms }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run collector
        run: |
          node -v
          node collect_last13_all_subjects.js

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: myquest-last${{ env.YEARS_BACK }}-${{ env.EXAM }}
          path: |
            outputs/${{ env.EXAM }}/**
